server:
  port: 8082

springdoc:
  api-docs:
    path: /rb-fee-collect-openapi
  swagger-ui:
    path: /rakbank/api/fee-collect/swagger-ui.html

spring:
  datasource:
    url: jdbc:h2:mem:feedb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

fee-collect:
  service:
    student:
      url: http://localhost:8080/rakbank/api/student/
